const ROUTES = {
  HOME: 'HOME',
  UPLOAD_DOCUMENTS: 'UPLOAD_DOCUMENTS',
  EXPERTS: 'EXPERTS',
  INSIGHTS: 'INSIGHTS',
  ANALYSING: 'ANALYSING',
  ANALYSIS_REPORT: 'ANALYSIS_REPORT',
  LANGUAGE: 'LANGUAGE',
  START_CONVERSATION: 'START_CONVERSATION',
  DETAILED_INSIGHTS: 'DETAILED_INSIGHTS',
};

export {ROUTES};
